set(CMAKE_SYSTEM_NAME Linux)
set(ENV linux)
set(ENV_KERNEL linux)
set(WINDOW_SYSTEM x11)
if(NOT PACK_DYN_RELOCS)
	set(PACK_DYN_RELOCS relr)
endif()

string(APPEND CFLAGS_COMMON " -D_GNU_SOURCE")
string(APPEND CFLAGS_CODEGEN " -pthread")
string(APPEND LDFLAGS " -lm -fuse-ld=mold \
-Wl,-O3,--gc-sections,--as-needed,--icf=all,--exclude-libs=ALL,--pack-dyn-relocs=${PACK_DYN_RELOCS}")

if(NOT CMAKE_C_COMPILER)
	find_program(LINUX_CC NAMES ${CTARGET}-gcc-16 gcc-16)
	find_program(LINUX_CXX NAMES ${CTARGET}-g++-16 g++-16)
	if(NOT LINUX_CC OR NOT LINUX_CXX)
		find_program(LINUX_CC NAMES ${CTARGET}-clang clang REQUIRED)
		find_program(LINUX_CXX NAMES ${CTARGET}-clang++ clang++ REQUIRED)
	endif()
	set(CMAKE_C_COMPILER ${LINUX_CC})
	set(CMAKE_CXX_COMPILER ${LINUX_CXX})
	find_program(LINUX_AR NAMES ${CTARGET}-gcc-ar gcc-ar llvm-ar)
	if(LINUX_AR)
		set(CMAKE_AR ${LINUX_AR})
	endif()
	find_program(LINUX_RANLIB NAMES ${CTARGET}-gcc-ranlib gcc-ranlib llvm-ranlib)
	if(LINUX_RANLIB)
		set(CMAKE_RANLIB ${LINUX_RANLIB})
	endif()
	find_program(LINUX_STRIP NAMES ${CTARGET}-strip strip)
	if(LINUX_STRIP)
		set(CMAKE_STRIP ${LINUX_STRIP})
	endif()
	find_program(LINUX_OBJDUMP NAMES ${CTARGET}-objdump objdump)
	if(LINUX_OBJDUMP)
		set(CMAKE_OBJDUMP ${LINUX_OBJDUMP})
	endif()
endif()

string(FIND "${CMAKE_C_COMPILER}" clang clangSubStringPos)
if(${clangSubStringPos} GREATER -1)
	# Glibc's fortify source macro causes internal linkage errors when building the std module
	string(APPEND CXXFLAGS " -stdlib=libc++ -D_FORTIFY_SOURCE=0")
	include("${CMAKE_CURRENT_LIST_DIR}/clang.cmake")
else()
	include("${CMAKE_CURRENT_LIST_DIR}/gcc.cmake")
endif()
